---
title: "Exploring Raw Tree Data"
author: "Briana Barajas"
date: 2024-01-28
---

## Preparation

Set-up chunk

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

Load libraries=

```{r}
library(tidyverse)
library(here)
```

Read in Data

```{r}
# read in tree ring data
rwi_long <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "rwi_long.csv"))

# read in site summary table
site_summary <- read_table(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "site_summary.tab"))

# read in species metadata
species_metadata <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "species_metadata.csv"))

# essential cwd data
essential_cwd <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "essentialcwd_data.csv"))

```

## Selecting Tree Species

```{r}
# capitalize`sp_id` column in species metadata ----
species_metadata <- species_metadata %>% 
  rename(sp_id = species_id) %>% 
  mutate(sp_id = toupper(sp_id))

# remove quotes from columns in site data ----
site_summary <- site_summary %>% 
  mutate(collection_id = str_remove_all(collection_id, "\""),
         sp_id = str_remove_all(sp_id, "\""))

# join data ---
rwi_species <- rwi_long %>% 
  
  # drop extra columns
  select(c(collection_id, year, rwi)) %>% 
  
  # join rwi to site_summary by collection id
  left_join(y = site_summary, by = 'collection_id') %>% 
  
  # drop extra columns
  select(collection_id, rwi, latitude, longitude, sp_id) %>% 
  
  # join with species metadata
  left_join(y = species_metadata, by = "sp_id") %>% 
  
  # drop select columns
  select(-c(source, gymno_angio, family, source))
```


```{r, plot top spp}
# create df with counts of collection ID
sp_count <- plyr::count(rwi_species$spp) %>% 
  rename(spp = x)

# plot top 15 collection ID counts
sp_count %>% 
  drop_na(spp) %>% 
  slice_max(order_by = freq, n = 20) %>% 
  ggplot() +
  geom_col(aes(x = fct_reorder(spp, freq), y = freq)) +
  labs(x = "Genus Species",
       y = "Number of Samples",
       title = "20 Most Sampled Species") +
  geom_text(aes(x = fct_reorder(spp, freq), y = freq,
                label = freq), hjust = 1.2, color = "white", size = 2.5) +
  coord_flip() +
  theme_minimal() 
```



