---
title: "Fletcher's Markdown"
author: "Fletcher McConnell"
date: 2024-01-28
---

## Preparation

Load libraries
```{r}
library(tidyverse)
library(here)
library(dplyr)
```


Read in Data
```{r}
# read in tree ring data
rwi_long <- read_csv(here("~/../../capstone/climatree/dataverse-archive/rwi_long.csv"))

# view tree ring data head
glimpse(rwi_long, 2)
```

```{r}
# Find all unique species and counts of collection sites for each 
prefix_counts <- rwi_long %>%
  mutate(prefix = gsub("\\d.*", "", collection_id)) %>% # Extract the prefix
  distinct(prefix, collection_id, .keep_all = TRUE) %>%  # Keep only distinct rows based on prefix and collection_id
  group_by(prefix) %>%
  summarise(count = n_distinct(collection_id))
```

```{r}
# Find 20 species with most collection sites
top_20 <- prefix_counts %>%
  top_n(20, count) %>% 
  arrange(desc(count))
```

```{r}
# display top 20 in histogram
ggplot(top_20, aes(x = fct_reorder(prefix, +count), y = count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab("Tree Species") +
  labs(title = "Top 20 Tree Species by Number of Collection Sites")

```

