---
title: 'Preliminary map for species'
subtitle: 'norway spruce: PCAB'
author: 'Rosemary Juarez'
output: pdf

---

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```


```{r message = FALSE}
library(tidyverse)
library(here)

library(sf)     # vector data
library(terra)  # raster data
library(tmap)   # mapping
```


#reading in data
```{r message = FALSE}
## ==================================================
##                 read in data                  ----
## ==================================================
# read in tree ring data
rwi_long <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "rwi_long.csv"))

# read in site summary table
site_smry <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "site_summary.csv"))

# read in species metadata
species_metadata <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "species_metadata.csv"))
```

### Wrangle and Join pipa Data

```{r}
## ==================================================
##                 prep for join                ----
## ==================================================

# ...... update species metadata ......
species_metadata <- species_metadata %>% 
  rename(sp_code = species_id)


# ..... update site smry data .....
site_smry <- site_smry %>%
  select(collection_id, sp_id) %>% 
  mutate(location_id = collection_id) %>%
  
  # change sp_id to lower case
  mutate(sp_code = tolower(sp_id)) %>% 
  
  # remove sp_id column
  select(-sp_id) %>%
  
  # remove quotes around strings
  mutate(collection_id = str_remove_all(collection_id, "\""),
         sp_code = str_remove_all(sp_code, "\""),
         location_id = str_remove_all(location_id, "\""))


## ==================================================
##                   join data                   ----
## ==================================================

# ..... join rwi, metadata, and site summary .....
rwi_species <- rwi_long %>% 
  
  # join rwi to site_summary by collection id
  left_join(y = site_smry, by = 'collection_id') %>% 
  
  #join with species metadata
  left_join(y = species_metadata, by = "sp_code") #%>%
```


## Export Subset

```{r psme subset}
## ==================================================
##                 create psme subset            ----
## ==================================================
# subset most sampled species
pcab_rwi <- rwi_species %>% 
  filter(spp == "Picea abies")

## ==================================================
##           export subset to prelim-maps       ----
## ==================================================
write_csv(pcab_rwi, here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "pcab_rwi.csv"))
```

## Load Data

```{r}
# load pcab rwi
pcab_rwi <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "pcab_rwi.csv"))

# essential cwd data (3b.R site-specific historic climate data)
site_clim <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "essentialcwd_data.csv"))
```

```{r read range shp}
## ==================================================
##                 PSME range map                ----
## ==================================================

# define query for psme range
query <- "SELECT * FROM merged_ranges_dissolve WHERE sp_code='pcab'"




# read in psme geometry data
pcab_range <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp"), query = query) %>% 
  st_make_valid()


# ===================================
#           group codes
#====================================

# Vanessa's range
pcgl_query <- "SELECT * FROM merged_ranges_dissolve WHERE sp_code='pcgl'"

pcgl_range <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp"), query = pcgl_query) %>% 
  st_make_valid()

pcgl_range <- st_union(pcgl_range)

#fletcher's range
pisy_query <- "SELECT * FROM merged_ranges_dissolve WHERE sp_code='pisy'"

pisy_range <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp"), query = pisy_query) %>% 
  st_make_valid()

pisy_range <- st_union(pisy_range)

#Bri's range
pcma_query <- "SELECT * FROM merged_ranges_dissolve WHERE sp_code='pcma'"

pcma_range <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp"), query = pcma_query) %>% 
  st_make_valid() 

pcma_range <- st_union(pcma_range)

# plot psme range
tm_shape(pcgl_range) +
  tm_polygons()

tm_shape(pcma_range)+
  tm_polygons()
```



```{r}
world <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp")) %>% 
  st_make_valid()
```



```{r}
###==============================================

#                 Data wrangling

#================================================

world_boundaries <- st_union(world)



```







```{r}

#st_transform(world, crs = 3857)

data("World")

tm_shape(World) +
  tm_polygons(col = 'pink', border.col = 'pink') +
  tm_shape(world)+
  tm_polygons(col = 'seagreen', border.col = 'seagreen') +
  tm_shape(pcab_range)+
  tm_polygons(col = 'navy', border.col = 'navy') +
  tm_shape(pcgl_range) +
  tm_polygons(col = 'orange', border.col = 'orange') + 
  tm_shape(pcma_range) +
  tm_polygons(col = 'cyan', border.col = 'cyan') +
  tm_shape(pisy_range) +
  tm_polygons(col = 'purple', border.col = 'purple') +
  tm_style('cobalt')



#'pcgl' -vanessa
#'pcma' - bri 
#'pisy' - fletcher


```

```{r}
tm_shape(World) +
  tm_polygons() +
  tm_style("classic") +
  tm_shape(world)+
  tm_polygons(col = 'green') +
  tm_shape(pcab_range)+ #Rosemary
  tm_fill(col = NA, alpha = 0) +
  tm_borders(col = 'navy', lwd = 1) +
  tm_shape(pcgl_range) + # Vanessa
  tm_fill(col = NA, alpha = 0)+
  tm_borders(col = 'orange') +
  tm_shape(pcma_range) + #bri
  tm_fill(col = NA, alpha = 0) +
  tm_borders(col = "cyan")+
  tm_shape(pisy_range)+ # Fletcher
  tm_fill(col = NA, alpha = 0) +
  tm_borders(col = 'green')
```

```{r}

tm_shape(World) +
  tm_polygons() +
  tm_style("classic")+
  

  tm_shape(world_boundaries)+
  tm_fill(col = 'green') +
  tm_borders() +
  
 #Rosemary
#  tm_shape(pcab_range)+
 # tm_fill(col = 'seagreen') +
  #tm_borders(col = 'navy', lwd = 1) #+
  #tm_polygons()+
  
#Vanessa
# tm_shape(pcgl_range) +
# tm_fill(col = 'seagreen')+
# tm_borders(col = 'navy', lwd = 1)
  
#bri
 # tm_shape(pcma_range) +
  #tm_fill(col = 'seagreen') +
  #tm_borders(col = "navy", lwd = 1) #+
  #tm_polygons()+
  
#fletcher
  tm_shape(pisy_range)+ # Fletcher
  tm_fill(col = 'seagreen') +
  tm_borders(col = 'navy') # +
  #tm_polygons()



```

```{r}
tmap_save(world_range, 'world_range.jpg')
```

```{r}
tm_shape()
```


