---
title: 'Preliminary map for species'
subtitle: 'Pinus ponderosa / PIPO / ponderosa pine'
author: 'Rosemary Juarez'
output: pdf

---

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

```


```{r message = FALSE}
library(tidyverse)
library(here)

library(sf)     # vector data
library(terra)  # raster data
library(tmap)   # mapping
```


#reading in data
```{r}
## ==================================================
##                 read in data                  ----
## ==================================================
# read in tree ring data
rwi_long <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "rwi_long.csv"))

# read in site summary table
site_smry <- read_table(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "site_summary.tab"))

# read in species metadata
species_metadata <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "species_metadata.csv"))
```

### Wrangle and Join pipa Data

```{r}
## ==================================================
##                 prep for join                ----
## ==================================================

# ...... update species metadata ......
species_metadata <- species_metadata %>% 
  rename(sp_code = species_id)


# ..... update site smry data .....
site_smry <- site_smry %>%
  select(collection_id, sp_id) %>% 
  mutate(location_id = collection_id) %>%
  
  # change sp_id to lower case
  mutate(sp_code = tolower(sp_id)) %>% 
  
  # remove sp_id column
  select(-sp_id) %>%
  
  # remove quotes around strings
  mutate(collection_id = str_remove_all(collection_id, "\""),
         sp_code = str_remove_all(sp_code, "\""),
         location_id = str_remove_all(location_id, "\""))


## ==================================================
##                   join data                   ----
## ==================================================

# ..... join rwi, metadata, and site summary .....
rwi_species <- rwi_long %>% 
  
  # join rwi to site_summary by collection id
  left_join(y = site_smry, by = 'collection_id') %>% 
  
  #join with species metadata
  left_join(y = species_metadata, by = "sp_code") #%>%
```


## Export Subset

```{r psme subset}
## ==================================================
##                 create psme subset            ----
## ==================================================
# subset most sampled species
pipo_rwi <- rwi_species %>% 
  filter(spp == "Pinus ponderosa")

## ==================================================
##           export subset to prelim-maps       ----
## ==================================================
write_csv(pipo_rwi, here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "pipo_rwi.csv"))
```

## Load Data

```{r}
# load psme rwi
pipo_rwi <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "pipo_rwi.csv"))

# essential cwd data (3b.R site-specific historic climate data)
site_clim <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "essentialcwd_data.csv"))
```

```{r read range shp}
## ==================================================
##                 PSME range map                ----
## ==================================================

# define query for psme range
query <- "SELECT * FROM merged_ranges_dissolve WHERE sp_code='psme' "

# read in psme geometry data
psme_range <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp"), query = query) %>% 
  st_make_valid()

# plot psme range
tm_shape(psme_range) +
  tm_polygons()
```
