```{r}
library(sf)
library(tmap)
library(terra)
library(tidyverse)
library(here)
```

```{r}
# load psme rwi
pisy_rwi <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "pisy_rwi.csv"))

# essential cwd data (3b.R site-specific historic climate data)
site_clim <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "essentialcwd_data.csv"))
```

```{r}
## ==================================================
##                 PSME range map                ----
## ==================================================

# define query for psme range
query <- "SELECT * FROM merged_ranges_dissolve WHERE sp_code='pisy' "

# read in psme geometry data
pisy_range <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive",  "merged_ranges_dissolve.shp"), query = query) %>% 
  st_make_valid()

# plot psme range
tm_shape(pisy_range) +
  tm_polygons()
```

```{r}
## ==================================================
##              prep clim raster data           ----
## ==================================================

# ..... read in climate files .....             ----
load(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "HistoricCWD_AETGrids_Annual.Rdat"))
```

```{r}
# take mean of raster stack (combine years?)
cwd_historic <- mean(cwd_historic) 
aet_historic <- mean(aet_historic)

# calc historic pet ----
pet_historic <- aet_historic + cwd_historic

# plot data ----
tm_shape(pet_historic) +
  tm_raster() +
  tm_shape(pisy_range) +
  tm_polygons()
```








## Running Part 3b of Treeconomics Script ----









```{r}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Authors: Robert Heilmayr, Frances Moore, Joan Dudney
# Project: Treeconomics
# Date: 5/1/20
# Purpose: 1) Characterize climate niche for different species. 
#          2) Standardize annual site data, baseline raster, and CMIP predictions for each species
#
# Input files:
#   merged_ranges.shp:
#   HistoricCWD_AETGrids_Annual.Rdat: Rasters describing historic CWD and AET
#     Generated using historic_cwdraster.R
#   monthlycrubaseline_tas:
#   cmip5_cwdaet_start.Rdat:
#   cmip5_cwdaet_end.Rdat:
#   essentialcwd_data.csv:
#   site_summary.csv:
# 
# Output files:
#   clim_niche.csv: Tabulation of each species' historic climate niche. Parameters used for standardization.
#   sp_clim_predictions.gz: Dataset describing species' standardized historic climate and their predicted climate under CMIP5 across species' full range
#   site_ave_clim.gz: Tables describing each site's species-standardized average historic climate
#   site_an_clim.gz: Tables describing each site's annual species-standardized weather
# 
# 
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Package imports --------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
library(tidyverse)
library(dbplyr)
library(RSQLite)
library(ggplot2)
library(sf)
library(here)
library(rgeos)
library(stringr)
library(raster)
library(readr)
library(tmap)
library(tictoc)
library(furrr)
select <- dplyr::select


library(furrr)
n_cores <- 8
future::plan(multisession, workers = n_cores)


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Load data --------------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Define path
#wdir <- 'remote/'

# 1. Historic climate raster
clim_file <- paste0(wdir, '1_input_processed/climate/HistoricCWD_AETGrids_Annual.Rdat')
load(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "HistoricCWD_AETGrids_Annual.Rdat"))
cwd_historic <- mean(cwd_historic)
aet_historic <- mean(aet_historic)
pet_historic <- aet_historic + cwd_historic
names(cwd_historic) = "cwd"
names(pet_historic) = "pet"

# 2. Data on historic baseline temp and precip
temps_historic <- raster(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "monthlycrubaseline_tas"))
names(temps_historic) = "temp"
temps_historic <- resample(temps_historic, cwd_historic)
clim_historic <- raster::brick(list(cwd_historic, pet_historic, temps_historic))

# 3. Site-specific historic climate data
site_clim_csv <- paste0(wdir, '1_input_processed/climate/essentialcwd_data.csv')
site_clim_df <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "essentialcwd_data.csv"))
site_clim_df <- site_clim_df %>% 
  mutate("site_id" = as.character(site)) %>% 
  rename(location_id = site_id)

site_smry <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive","site_summary.csv"))
site_smry <- site_smry %>%
  select(collection_id, sp_id) %>% 
  mutate(location_id = collection_id) %>% 
  mutate(sp_code = tolower(sp_id)) %>% 
  select(-sp_id)


## NOTE: FIA data not included in replication data repository
# site_smry_fia <- read_csv(paste0(wdir, 'out/dendro/site_summary_fia.csv'))
# site_smry_fia <- site_smry_fia %>% 
#   select(collection_id, location_id = plot_cn, sp_id = species_id) %>% 
#   mutate(sp_code = tolower(sp_id)) %>% 
#   select(-sp_id)
# site_smry <- rbind(site_smry, site_smry_fia)


# 5. Species range maps
range_file <- paste0(wdir, '1_input_processed/species_ranges/merged_ranges_dissolve.shp')
range_sf <- st_read(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "merged_ranges_dissolve.shp"))

# 6. Climate projections from CMIP5
cmip_end <- load(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "cmip5_cwdaet_end.Rdat"))
pet_cmip_end <- aet_raster + cwd_raster
cwd_cmip_end <- cwd_raster
names(cwd_cmip_end) <- NULL # Resetting this due to strange names in file from CMIP processing
rm(cwd_raster)
rm(aet_raster)

cmip_start <- load(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "cmip5_cwdaet_start.Rdat"))
pet_cmip_start <- aet_raster + cwd_raster
cwd_cmip_start <- cwd_raster
names(cwd_cmip_start) <- NULL # Resetting this due to strange names in file from CMIP processing
rm(cwd_raster)
rm(aet_raster)




# #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# # Visually inspect data -----------------------------------------------
# #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 tmap_mode("view")
 tm_shape(cwd_cmip_end) +
   tm_raster() +
   tm_facets(as.layers = TRUE)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Summarize species niches -----------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Pull and organize climate distribution for species
pull_clim <- function(spp_code){
  print(spp_code)
  # Pull relevant range map
  sp_range <- range_sf %>%
    filter(sp_code == spp_code) %>% 
    rasterize(cwd_historic, getCover=TRUE)
  sp_range[sp_range==0] <- NA
  
  # Pull cwd and aet values
  cwd_vals <- cwd_historic %>% 
    mask(sp_range) %>% 
    as.data.frame(xy = TRUE) %>% 
    drop_na()
  
  pet_vals <- pet_historic %>% 
    mask(sp_range) %>% 
    as.data.frame(xy = TRUE) %>% 
    drop_na()
  
  temp_vals <- temps_historic %>% 
    mask(sp_range) %>% 
    as.data.frame(xy = TRUE) %>% 
    drop_na()
  
  # Combine into tibble
  clim_vals <- cwd_vals %>% 
    left_join(pet_vals, by = c("x", "y")) %>% 
    left_join(temp_vals, by = c("x", "y"))
  
  return(clim_vals)
}


species_list <- range_sf %>%
  pull(sp_code) %>% 
  unique() %>% 
  enframe(name = NULL) %>% 
  select(sp_code = value) %>% 
  arrange(sp_code) %>% 
  drop_na()
-------------------------------------------------------------------------------------------------------
#clim_df <- species_list %>% 
  #mutate(clim_vals = future_map(sp_code, 
                                #.f = pull_clim,
                                #.options = furrr_options(packages = c( "dplyr", "raster", "sf")),
                                #.progress = TRUE))

clim_vals <- map(species_list$sp_code, pull_clim)

clim_df <- mutate(species_list, clim_vals = clim_vals)
--------------------------------------------------------------------------------------------------------

## Summarize mean and sd of each species' climate
niche_df <- clim_df %>% 
  unnest(clim_vals) %>% 
  group_by(sp_code) %>% 
  summarize(pet_mean = mean(pet),
            pet_sd = sd(pet),
            cwd_mean = mean(cwd),
            cwd_sd = sd(cwd),
            temp_mean = mean(temp),
            temp_sd = sd(temp))


## Export species niche description
#write.csv(niche_df, paste0(wdir, "2_output/climate/clim_niche.csv"))


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Standardize historic climate -------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
sp_standardize <- function(val, sp_mean, sp_sd){
  std_val <- (val - sp_mean) / sp_sd
  return(std_val)
}

sp_std_historic_df <- function(hist_clim_vals, pet_mean, pet_sd, cwd_mean, cwd_sd, temp_mean, temp_sd){
  hist_clim_vals <- hist_clim_vals %>% 
    mutate_at(vars(starts_with("cwd")), 
              ~sp_standardize(.x, cwd_mean, cwd_sd)) %>% 
    mutate_at(vars(starts_with("pet")), 
              ~sp_standardize(.x, pet_mean, pet_sd)) %>% 
    mutate_at(vars(starts_with("temp")), 
              ~sp_standardize(.x, temp_mean, temp_sd))
  return(hist_clim_vals)
}


sp_std_future_df <- function(cmip_df, hist_clim_vals, pet_mean, pet_sd, cwd_mean, cwd_sd, temp_mean, temp_sd){
  valid_locations <- hist_clim_vals %>% select(x,y)
  cmip_df <- valid_locations %>% 
    left_join(cmip_df, by = c("x", "y"))
  cmip_df <- cmip_df %>% 
    mutate_at(vars(starts_with("cwd")), 
              ~sp_standardize(.x, cwd_mean, cwd_sd)) %>% 
    mutate_at(vars(starts_with("pet")), 
              ~sp_standardize(.x, pet_mean, pet_sd)) %>% 
    mutate_at(vars(starts_with("temp")), 
              ~sp_standardize(.x, temp_mean, temp_sd))
  return(cmip_df)
}


clim_df <- clim_df %>% 
  left_join(niche_df, by = "sp_code")

clim_df <- clim_df %>% 
  mutate(clim_historic_sp = future_pmap(list(hist_clim_vals = clim_vals,
                                             pet_mean = pet_mean,
                                             pet_sd = pet_sd,
                                             cwd_mean = cwd_mean,
                                             cwd_sd = cwd_sd,
                                             temp_mean = temp_mean,
                                             temp_sd = temp_sd),
                                        .f = sp_std_historic_df,
                                        .options = furrr_options(packages = c( "dplyr"))))
# NOTE: May no longer need this dataframe???


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Pull CMIP projections -----------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_end_df <- pet_cmip_end %>% 
  as.data.frame(xy = TRUE) %>%
  drop_na() %>% 
  as_tibble() %>%
  rename_with(~stringr::str_replace(., "layer.", "pet_cmip_end"), 
              starts_with('layer.'))

cwd_end_df <- cwd_cmip_end %>% 
  as.data.frame(xy = TRUE) %>%
  drop_na() %>% 
  as_tibble() %>%
  rename_with(~stringr::str_replace(., "layer.", "cwd_cmip_end"), 
              starts_with('layer.'))


pet_start_df <- pet_cmip_start %>% 
  as.data.frame(xy = TRUE) %>%
  drop_na() %>% 
  as_tibble() %>%
  rename_with(~stringr::str_replace(., "layer.", "pet_cmip_start"), 
              starts_with('layer.'))

cwd_start_df <- cwd_cmip_start %>% 
  as.data.frame(xy = TRUE) %>%
  drop_na() %>% 
  as_tibble() %>%
  rename_with(~stringr::str_replace(., "layer.", "cwd_cmip_start"), 
              starts_with('layer.'))


# ## Illustrate forawrd/backward conversion between df and raster
# crs_template <- crs(cwd_future)
# raster_template <- cwd_df %>% select(x,y)
# cwd_df <- cwd_df %>% 
#   drop_na()
# cwd_df2 <- raster_template %>% 
#   left_join(cwd_df, by = c("x", "y"))
# cwd_rast2 <- rasterFromXYZ(cwd_df2, crs = crs_template)

## Combine PET and CWD projections
cmip_df <- cwd_end_df %>% 
  full_join(pet_end_df, by = c("x", "y")) %>% 
  full_join(cwd_start_df, by = c("x", "y")) %>% 
  full_join(pet_start_df, by = c("x", "y"))

## Nest CMIP data
cmip_df <- cmip_df %>%
  mutate(idx = 1) %>% 
  group_by(idx) %>% 
  nest() %>% 
  ungroup() %>% 
  select(data)


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Summarize cmip climate for each species ------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## Cross species list with nested cmip data
sp_cmip_clim <- clim_df %>% 
  mutate(cmip_df = cmip_df$data)



sp_cmip_clim <- sp_cmip_clim %>% 
  mutate(clim_cmip_sp = future_pmap(list(cmip_df = cmip_df,
                                         hist_clim_vals = clim_vals,
                                         pet_mean = pet_mean,
                                         pet_sd = pet_sd,
                                         cwd_mean = cwd_mean,
                                         cwd_sd = cwd_sd), 
                                    .f = sp_std_future_df,
                                    .options = furrr_options(packages = c( "dplyr")))) %>% 
  select(-cmip_df)


# ## Check final result as raster
# species = "acsh"
# test_clim <- (sp_cmip_clim %>% filter(sp_code == species) %>% pull(clim_cmip_sp))[[1]]
# crs_template <- crs(cwd_cmip_end)
# raster_template <- cwd_cmip_end %>% as.data.frame(xy = TRUE) %>% select(x,y)
# test_clim <- raster_template %>%
#   left_join(test_clim, by = c("x", "y"))
# test_clim <- rasterFromXYZ(test_clim, crs = crs_template)
# range <- range_sf %>% filter(sp_code == species)
# tmap_mode("view")
# 
# tm_shape(test_clim$cwd_cmip_end1) +
#   tm_raster(palette = "-RdYlGn") +
#   tm_facets(as.layers = TRUE) +
#   tm_shape(range) + 
#   tm_fill(col = "lightblue")
# 
# tm_shape(test_clim$cwd_cmip_end1) +
#   tm_raster(palette = "-RdYlGn") +
#   tm_facets(as.layers = TRUE) +
#   tm_shape(test_clim$cwd_cmip_start1) +
#   tm_raster(palette = "-RdYlGn") +
#   tm_facets(as.layers = TRUE) +
#   tm_shape(range) + 
#   tm_fill(col = "lightblue")


## Export predictions
#write_rds(sp_cmip_clim, paste0(wdir, "2_output/climate/sp_clim_predictions.", compress = "gz"))


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Apply species standardization to site-level data -----------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# niche_df <- niche_df %>% 
#   select(sp_code = sp_code, sp_pet_mean = pet_mean, sp_pet_sd = pet_sd, sp_cwd_mean = cwd_mean, sp_cwd_sd = cwd_sd)


# Calculate site-level annual climate
site_clim_df = site_clim_df %>%
  group_by(location_id, year) %>%
  summarise(aet.an = sum(aet),
            cwd.an = sum(cwd),
            pet.an = sum((aet+cwd)),
            temp.an = mean(tmean),
            .groups = "drop")


### Calculate site-level, average, historic, relative climate (for second stage)
## TODO: Note - dropping CANA323 because it has null climate data for a few months each year. might want to dig into this
site_clim_df <- site_clim_df %>% 
  filter(location_id != "CANA323")

ave_site_clim_df <- site_clim_df %>% 
  filter(year < 1980) %>% 
  group_by(location_id) %>% 
  summarise(cwd.ave = mean(cwd.an),
            pet.ave = mean(pet.an),
            cwd.sd = sd(cwd.an),
            pet.sd = sd(pet.an),
            temp.ave = mean(temp.an),
            temp.sd = sd(temp.an)) %>% 
  ungroup()

spstd_site_clim_df <- site_smry %>% 
  left_join(ave_site_clim_df, by = "location_id") %>% 
  group_by(sp_code) %>% 
  nest(data = c(collection_id, cwd.ave, pet.ave, temp.ave)) %>% 
  left_join(niche_df, by = ("sp_code")) %>%
  drop_na() # Dropping some species due to NA niche data

spstd_site_clim_df <- spstd_site_clim_df %>% 
  mutate(site_clim = future_pmap(list(hist_clim_vals = data,
                                      pet_mean = pet_mean,
                                      pet_sd = pet_sd,
                                      cwd_mean = cwd_mean,
                                      cwd_sd = cwd_sd,
                                      temp_mean = temp_mean,
                                      temp_sd = temp_sd),
                                 .f = sp_std_historic_df,
                                 .options = furrr_options(packages = c( "dplyr"))))

spstd_site_clim_df <- spstd_site_clim_df %>% 
  unnest(site_clim) %>% 
  rename(cwd.spstd = cwd.ave, pet.spstd = pet.ave, temp.spstd = temp.ave) %>% 
  mutate(cwd.sd = cwd.sd / cwd_sd,
         pet.sd = pet.sd / pet_sd,
         temp.sd = temp.sd / temp_sd) %>% 
  ungroup() %>% 
  select(collection_id, location_id, cwd.spstd, pet.spstd, temp.spstd, cwd.sd, pet.sd, temp.sd)

spstd_site_clim_df <- spstd_site_clim_df %>% 
  left_join(ave_site_clim_df %>% select(location_id, cwd.ave, pet.ave, temp.ave), by = "location_id")

spstd_site_clim_df <- spstd_site_clim_df %>% 
  select(-location_id)

#write_rds(spstd_site_clim_df, 
          #paste0(wdir, "2_output/climate/site_ave_clim.", compress = "gz"))





### Calculate site-level, annual, historic, relative climate (for first stage) 
an_site_clim_df <- site_smry %>% 
  left_join(site_clim_df, by = "location_id") %>% 
  group_by(sp_code) %>% 
  nest() %>% 
  left_join(niche_df, by = "sp_code") %>% 
  drop_na()

an_site_clim_df <- an_site_clim_df %>% 
  mutate(site_clim = future_pmap(list(hist_clim_vals = data,
                                      pet_mean = pet_mean,
                                      pet_sd = pet_sd,
                                      cwd_mean = cwd_mean,
                                      cwd_sd = cwd_sd,
                                      temp_mean = temp_mean,
                                      temp_sd = temp_sd),
                                 .f = sp_std_historic_df,
                                 .options = furrr_options(packages = c( "dplyr"))))

an_site_clim_df <- an_site_clim_df %>% 
  unnest(site_clim) %>% 
  rename(cwd.an.spstd = cwd.an, pet.an.spstd = pet.an, temp.an.spstd = temp.an) %>% 
  ungroup() %>% 
  select(-aet.an, -pet_mean, -pet_sd, -cwd_mean, -cwd_sd, -temp_mean, -temp_sd, -data, -sp_code)

an_site_clim_df <- an_site_clim_df %>%
  select(-location_id)

write_rds(an_site_clim_df, 
          paste0(wdir, "2_output/climate/site_an_clim.", compress = "gz"))

# Write file to ClimaTree directory
write_csv(an_site_clim_df, here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_an_clim.gz"))

# check to make sure we can open site_an_clim.gz
site_an_clim <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_an_clim.gz"))


# ## Exploring source of dropped sites - seems to be entirely driven by sites for species with no range maps
# an_site_clim_df %>% pull(collection_id) %>% unique() %>% length()
# site_clim_df %>% pull(collection_id) %>% unique() %>% length()
# # clim_sites <- clim_df %>% pull(collection_id) %>% unique()
# test_sites <- test %>% pull(collection_id) %>% unique()
# an_site_clim_df %>% unnest(cols = c(data)) %>% pull(collection_id) %>% unique() %>% length()
# an_site_clim_df %>% unnest(cols = c(data)) %>% drop_na() %>% pull(collection_id) %>% unique() %>% length()

```








# Running Part 4a of Treeconomics Script ----









```{r}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Authors: Robert Heilmayr, Frances Moore, Joan Dudney
# Project: Treeconomics
# Date: 5/1/20
# Purpose: Run plot-level regressions of RWI sensitivity to annual weather variability
#
# Input files:
# - site_an_clim.gz: File detailing site-level weather history. Generated using "3b. Species_niche.R"
# - rwi_long.csv: Data containing processed RWI data. Generated using "1b. Parse ITRDB.R"
# - site_summary.csv: Summary data about each site. Generated using "1b. Parse ITRDB.R"
#
# Output files:
# - example_sites.csv: Dendrochronologies for two example sites. Used for methods summary figure.
# - site_pet_cwd_std.csv: Table of first stage regression parameters for baseline specification.
# - site_pet_cwd_std_nb.csv: Table of first stage regression parameters for robustness model using NB desplining.
# - site_pet_cwd_std_ar.csv: Table of first stage regression parameters for robustness model using AR desplining.
# - site_temp_cwd_std.csv:Table of first stage regression parameters for robustness model using temperature in place of PET.
#
#
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Package imports --------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
library(tidyr)
library(tidyverse)
# library(tidylog)
library(dbplyr)
library(broom.mixed)
library(broom)
library(purrr)
library(fixest)
library(dtplyr)
library(furrr)
library(here)


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Import and integrate data --------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Define path
wdir <- 'remote/'


# 1. Dendrochronologies
dendro_dir <- paste0(wdir, "1_input_processed/dendro/")
dendro_df <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "rwi_long.csv"))
dendro_df <- dendro_df %>% 
  select(-core_id)

## Combine multiple cores from the same tree
dendro_df <- dendro_df %>% 
  lazy_dt() %>% 
  group_by(collection_id, tree, year) %>% 
  summarise(rwi = mean(rwi),
            rwl = mean(rwl),
            rwi_ar = mean(rwi_ar),
            rwi_nb = mean(rwi_nb),
            .groups = "drop") %>% 
  as_tibble()

# 2. Historic site-level climate
an_site_clim <- read_csv(gzfile(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_an_clim.gz")))
dendro_df <- dendro_df %>% 
  left_join(an_site_clim, by = c("collection_id", "year"))


# 3. Site information
site_smry <- read_csv(here("~","..", "..", "capstone", "climatree", "dataverse-archive", "site_summary.csv"))
site_smry <- site_smry %>% 
  select(collection_id, sp_id) %>% 
  mutate(species_id = tolower(sp_id)) %>% 
  select(-sp_id)

dendro_df <- dendro_df %>% 
  left_join(site_smry, by = 'collection_id')

---------------------------------------------------------------------------------------------
# 4. Drop data from species without range maps and resulting climatic niche data
#niche_df <- read.csv(paste0(wdir, "2_output/climate/clim_niche.csv")) %>%
  #select(-X)
#niche_species <- niche_df %>% pull(sp_code) %>% unique()
#dendro_species <- dendro_df %>% pull(species_id) %>% unique()
#dendro_df <- dendro_df %>% 
  #filter(species_id %in% niche_species)
----------------------------------------------------------------------------------------------


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Export example sites for presentations  ------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
---------------------------------------------------
#ex_sites <- c("CO559", "CA585")
#dendro_df %>% 
  #filter(collection_id %in% ex_sites) %>% 
  #write.csv(paste0(wdir, "2_output/first_stage/example_sites.csv"))
--------------------------------------------------------------


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Define regression model  -------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fs_mod <- function(site_data, outcome = "rwi", energy_var = "pet.an", mod_type = "lm"){
  failed <- F
  reg_error <- NA
  nobs <- NA
  ntrees <- site_data %>% select(tree) %>%  n_distinct()
  no_cwd_var <- (site_data %>% select(cwd.an) %>% n_distinct() == 1)
  no_pet_var <- (site_data %>% select(energy_var) %>% n_distinct() == 1)
  
  if (no_cwd_var | no_pet_var) {
    message(paste0("Site has no variation in cwd.an or ", energy_var))
    failed <- T
  } else{
    # Try to run felm. Typically fails if missing cwd / pet data 
    tryCatch(
      expr = {
        formula <- as.formula(paste0(outcome, " ~ ", energy_var, " + cwd.an"))
        if (mod_type == "lm"){
          mod <- lm(formula, data = site_data)
        }
        if (mod_type == "lme"){
          mod <- nlme::lme(formula,
                           data=site_data, method="REML",
                           random = ~ 1 | tree,
                           correlation = nlme::corAR1(form=~year|tree))
        }
        
        mod_sum <- summary(mod)
        mod_vcov <- vcov(mod)
        # cov <- list(int_cwd = mod_vcov[1, 2], 
        #             int_pet = mod_vcov[1, 3], 
        #             pet_cwd = mod_vcov[2, 3])
        nobs <- nobs(mod)
        mod <- tidy(mod) %>%
          mutate(term = term %>% str_replace("\\(Intercept\\)", "intercept")) %>% 
          filter(term %in% c('intercept', 'cwd.an', energy_var)) %>% 
          pivot_wider(names_from = "term", values_from = c("estimate", "std.error", "statistic", "p.value"))
        # mod <- mod %>% 
        #   rename_all(funs(stringr::str_replace_all(., energy_var, 'energy.an')))
        mod$cov_int_cwd = mod_vcov[c("(Intercept)"), c("cwd.an")]
        cov_var_name <- paste0("cov_int_", energy_var %>% str_replace(".an", ""))
        mod[[cov_var_name]] = mod_vcov[c("(Intercept)"), c(energy_var)]
        cov_var_name <- paste0("cov_cwd_", energy_var %>% str_replace(".an", ""))
        mod[[cov_var_name]] = mod_vcov[c("cwd.an"), c(energy_var)]
        mod$r2 = mod_sum$r.squared
      },
      error = function(e){ 
        message("Returned regression error")
        reg_error <<- e[1]
        failed <<- T
      }
    )    
  }
  if (failed){
    return(NA)
  }
  return(tibble(mod = list(mod), nobs = nobs, ntrees = ntrees, error = reg_error))
}


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Run site-level regressions --------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

site_df <- dendro_df %>% 
  # drop_na() %>% 
  rename(cwd.an = cwd.an.spstd,
         pet.an = pet.an.spstd,
         temp.an = temp.an.spstd) %>% 
  group_by(collection_id) %>%
  add_tally(name = 'nobs') %>% 
  # filter(nobs>10) %>% 
  nest()


fs_mod_bl <- partial(fs_mod, outcome = "rwi", energy_var = "pet.an", mod_type = "lm")
fs_mod_nb <- partial(fs_mod, outcome = "rwi_nb", energy_var = "pet.an", mod_type = "lm")
fs_mod_ar <- partial(fs_mod, outcome = "rwi_ar", energy_var = "pet.an", mod_type = "lm")
fs_mod_temp <- partial(fs_mod, outcome = "rwi", energy_var = "temp.an", mod_type = "lm")
fs_mod_re <- partial(fs_mod, outcome = "rwi", energy_var = "pet.an", mod_type = "lme")
--------------------------------------------------------
site_df <- site_df %>% 
  mutate(fs_result = map(data, .f = fs_mod_bl))
         #fs_result_nb = map(data, .f = fs_mod_nb),
         #fs_result_ar = map(data, .f = fs_mod_ar),
         #fs_result_temp = map(data, .f = fs_mod_temp),
         #fs_result_re = map(data, .f = fs_mod_re))
--------------------------------------------------------

data_df <- site_df %>% 
  select(collection_id,data)

fs_df <- site_df %>% 
  select(collection_id, fs_result) %>% 
  unnest(fs_result)

fs_df <- fs_df[which(!(fs_df %>% pull(mod) %>% is.na())),]
fs_df <- fs_df %>% 
  unnest(mod)

fs_df <- fs_df %>% 
  select(-error)
--------------------------------------------------------------------------------------
fs_df %>% write_csv(paste0(wdir, '2_output/first_stage/site_pet_cwd_std.csv'))

fs_df %>% write_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_pet_cwd_std.csv"))

site_pet_cwd_std <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_pet_cwd_std.csv"))

output <- full_join(site_pet_cwd_std, site_smry, by = "collection_id")

output_pisy <- output %>% 
  filter(species_id %in% "pisy")
--------------------------------------------------------------------------------------

## Repeat using results from nb detrended data
fs_nb <- site_df %>% 
  select(collection_id, fs_result_nb) %>% 
  unnest(fs_result_nb)
fs_nb <- fs_nb[which(!(fs_nb %>% pull(mod) %>% is.na())),]
fs_nb <- fs_nb %>% 
  unnest(mod) %>% 
  select(-error)
fs_nb %>% write_csv(paste0(wdir, '2_output/first_stage/site_pet_cwd_std_nb.csv'))


## Repeat using results from ar detrended data
fs_ar <- site_df %>% 
  select(collection_id, fs_result_ar) %>% 
  unnest(fs_result_ar)
fs_ar <- fs_ar[which(!(fs_ar %>% pull(mod) %>% is.na())),]
fs_ar <- fs_ar %>% 
  unnest(mod) %>% 
  select(-error)
fs_ar %>% write_csv(paste0(wdir, '2_output/first_stage/site_pet_cwd_std_ar.csv'))


## Repeat using results from temp model
fs_temp <- site_df %>% 
  select(collection_id, fs_result_temp) %>% 
  unnest(fs_result_temp)
fs_temp <- fs_temp[which(!(fs_temp %>% pull(mod) %>% is.na())),]
fs_temp <- fs_temp %>% 
  unnest(mod) %>% 
  select(-error)
fs_temp %>% write_csv(paste0(wdir, '2_output/first_stage/site_temp_cwd_std.csv'))


## Repeat using results from re model
fs_re <- site_df %>% 
  select(collection_id, fs_result_re) %>% 
  unnest(fs_result_re)
fs_re <- fs_re[which(!(fs_re %>% pull(mod) %>% is.na())),]
fs_re <- fs_re %>% 
  unnest(mod) %>% 
  select(-error)
fs_re %>% write_csv(paste0(wdir, '2_output/first_stage/site_pet_cwd_std_re.csv'))

```








# Running Second Stage 5a from Script ----








```{r}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Authors: Robert Heilmayr, Joan Dudney, Frances Moore
# Project: Treeconomics
# Date: 5/17/20
# Purpose: Run regressions to explore impact of historical climate on weather sensitivity
#
# Input files:
# - site_pet_cwd_std.csv: Table of first stage regression parameters for baseline specification. Generated in "4a". First stage.R"
# - site_ave_clim.gz: Site-level climate parameters. Generated using "3b. Species_niche.R"
# - site_summary.csv: Summary data about each site. Generated using "1b. Parse ITRDB.R"
# - species_gen_gr.csv: Lookup key for angiosperm / gymnosperm differentiation
# 
# Output files:
# - site_pet_cwd_std_augmented.csv: Intermediate file to enable downstream identification of outlier assignment.
# - mc_sample.gz: Intermediate file of all bootstrapped samples.
# - ss_bootstrap.rds: Final second stage model parameters for each of n_mc Monte Carlo runs.
#
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Package imports --------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
library(MASS)
library(tidyverse)
library(broom)
library(purrr)
library(margins)
library(tidylog)
library(fixest)
library(gstat)
library(sf)
library(units)
library(dtplyr)
library(marginaleffects)

set.seed(5597)

select <- dplyr::select

n_mc <- 10000


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Import data --------------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
### Define path
wdir <- 'remote/'

# 1. Site-level regressions
flm_df <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_pet_cwd_std.csv"))

# 2. Historic site-level climate
ave_site_clim <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_an_clim.gz"))

flm_df <- flm_df %>% 
  left_join(ave_site_clim, by = c("collection_id"))

# 3. Site information
site_df <- read_csv(here("~", "..", "..", "capstone", "climatree", "dataverse-archive", "site_summary.csv"))
site_df <- site_df %>% 
  select(collection_id, sp_id, latitude, longitude)
site_df <- site_df %>% 
  rename(species_id = sp_id) %>% 
  mutate(species_id = str_to_lower(species_id))

# # 4. Species information
# sp_info <- read_csv(paste0(wdir, 'species_gen_gr.csv'))
# sp_info <- sp_info %>% 
#   select(species_id, genus, gymno_angio, family)
# site_df <- site_df %>% 
#   left_join(sp_info, by = "species_id")

# Merge back into main flm_df
flm_df <- flm_df %>% 
  left_join(site_df, by = "collection_id")



#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Prep and trim data -----------------------------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Add weighting based on inverse of first stage variance
flm_df <- flm_df %>% 
  mutate(cwd_errorweights = 1 / (std.error_cwd.an),
         errorweights2 = sqrt(ntrees),
         pet_errorweights = 1 / (std.error_pet.an),
         int_errorweights = 1 / (std.error_intercept))

# Identify and trim extreme outliers
cwd_est_bounds = quantile(flm_df$estimate_cwd.an, c(0.01, 0.99),na.rm=T)
pet_est_bounds = quantile(flm_df$estimate_pet.an, c(0.01, 0.99),na.rm=T)
cwd_spstd_bounds = quantile(flm_df$cwd.spstd, c(0.01, 0.99), na.rm = T)
pet_spstd_bounds = quantile(flm_df$pet.spstd, c(0.01, 0.99), na.rm = T)

# flm_df <- flm_df %>%
#   mutate(outlier = (estimate_cwd.an<cwd_est_bounds[1]) |
#            (estimate_cwd.an>cwd_est_bounds[2]) |
#            (estimate_pet.an<pet_est_bounds[1]) |
#            (estimate_pet.an>pet_est_bounds[2]) |
#            (cwd.spstd<cwd_spstd_bounds[1]) |
#            (cwd.spstd>cwd_spstd_bounds[2]) |
#            (pet.spstd<pet_spstd_bounds[1]) |
#            (pet.spstd>pet_spstd_bounds[2]))
           

flm_df <- flm_df %>%
  mutate(outlier = (estimate_cwd.an<cwd_est_bounds[1]) |
                   (estimate_cwd.an>cwd_est_bounds[2]) |
                   (estimate_pet.an<pet_est_bounds[1]) |
                   (estimate_pet.an>pet_est_bounds[2]))

# Save out full flm_df to simplify downstream scripts and ensure consistency
flm_df %>% write.csv(paste0(wdir, "2_output/first_stage/site_pet_cwd_std_augmented.csv"))

flm_df %>% write_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_pet_cwd_std_augmented.csv"))

# Trim outliers
trim_df <- flm_df %>% 
  filter(outlier==0) %>% 
  drop_na()


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Spatial autocorrelation of trim_df ---------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
site_points=st_as_sf(trim_df,coords=c("longitude","latitude"),crs="+init=epsg:4326 +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0")

vg <-variogram(estimate_cwd.an~1, site_points, cutoff = 1500, width = 10)
vg.fit <- fit.variogram(vg, model = vgm(1, "Sph", 900, 1))
plot(vg, vg.fit)
# print(paste0("Range before hitting sill (km): "), as.character(vg.fit[2,3]))

vg.range = vg.fit[2,3] * 1000


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Quick test of primary regression ---------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
formula = as.formula("estimate_cwd.an ~ cwd.an.spstd + (cwd.an.spstd^2) + pet.an.spstd + (pet.an.spstd^2)")
mod_data <- trim_df
cwd_mod <- feols(formula, data = mod_data, weights = mod_data$cwd_errorweights,
             vcov = conley(cutoff = vg.range/1000, distance = "spherical"))
summary(cwd_mod)

marg_fx_df <- function(mod){
  inc <- 0.1
  min <- -2.5
  max <- 2.5
  cwd_pred <- predictions(mod, newdata = datagrid(pet.spstd = 0, cwd.spstd = seq(min,max,inc))) %>% 
    mutate(variation = "cwd")
  pet_pred <- predictions(mod, newdata = datagrid(pet.spstd = seq(min,max,inc), cwd.spstd = 0)) %>% 
    mutate(variation = "pet")
  return(rbind(cwd_pred, pet_pred))
}


preds <- marg_fx_df(cwd_mod)

cwd_mfx_plot <- preds %>% 
  filter(variation == "cwd") %>% 
  ggplot(aes(x = cwd.spstd)) + 
  geom_line(aes(y = estimate)) +
  geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.2)
cwd_mfx_plot

pet_mfx_plot <- preds %>% 
  filter(variation == "pet") %>% 
  ggplot(aes(x = pet.spstd)) + 
  geom_line(aes(y = estimate)) +
  geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.2)
pet_mfx_plot

formula = as.formula("estimate_pet.an ~ cwd.spstd + pet.spstd + (cwd.spstd^2) + (pet.spstd^2)")
pet_mod <- feols(formula, weights = mod_data$pet_errorweights, data = mod_data,
                 vcov = conley(cutoff = vg.range/1000, distance = "spherical"))
summary(pet_mod)
preds <- marg_fx_df(pet_mod)

cwd_mfx_plot <- preds %>% 
  filter(variation == "cwd") %>% 
  ggplot(aes(x = cwd.spstd)) + 
  geom_line(aes(y = estimate)) +
  geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.2)
cwd_mfx_plot

pet_mfx_plot <- preds %>% 
  filter(variation == "pet") %>% 
  ggplot(aes(x = pet.spstd)) + 
  geom_line(aes(y = estimate)) +
  geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.2)
pet_mfx_plot

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Identify spatially proximate blocks of sites ---------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
site_list <- trim_df %>%
  pull(collection_id) %>%
  unique()
n_sites <- length(site_list)

site_dist=st_distance(site_points)
rownames(site_dist)=site_points$collection_id
colnames(site_dist)=site_points$collection_id
# save(site_dist,file=paste0(wdir,"out/site_distances.Rdat"))
# load(paste0(wdir,"out/site_distances.Rdat"))

dist_df <- as_tibble(site_dist) %>% 
  drop_units() 

dist_df <- dist_df %>%
  lazy_dt() %>% 
  mutate(collection_id = names(dist_df)) %>% 
  # select(collection_id, site_list) %>% 
  # filter(collection_id %in% site_list) %>% 
  mutate(across(.cols = !collection_id, ~(.x < vg.range))) %>% 
  # mutate(across(.cols = !collection_id, ~ifelse((.x < range), collection_id, "DROP"))) %>% 
  as_tibble()

block_list <- c()
for (site in site_list){
  block_sites <- dist_df %>% 
    filter(get(site) == TRUE) %>% 
    pull(collection_id)
  block_list[site] <- list(block_sites)
}
save(block_list,file=paste0(wdir,"2_output/second_stage/spatial_blocks.Rdat"))
# load(file=paste0(wdir,"out/second_stage/spatial_blocks.Rdat"))


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Create block bootstrap draws  ---------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
draw_blocks <- function(site_sample){
  samp <- site_sample %>% pull(samp)
  blocked_draw <- (block_list[samp] %>% unlist() %>% unname())[1:n_sites]
  return(blocked_draw)  
}

n_obs = n_mc * n_sites
block_draw_df <- tibble(boot_id = rep(1:n_mc, each = n_sites)) %>% 
  lazy_dt() %>% 
  mutate(samp = sample(site_list,size=n_obs,replace=TRUE)) %>%
  group_by(boot_id) %>% 
  nest()

block_draw_df <- block_draw_df %>% 
  mutate(sites = map(.x = data, .f = draw_blocks)) %>% # COULD PARALLELIZE HERE?
  select(boot_id, sites) %>% 
  as_tibble() %>% 
  unnest(sites) 

block_draw_df <- block_draw_df %>% 
  rename(collection_id = sites)

## Identify number of draws needed for each site
n_draws <- block_draw_df %>% 
  group_by(collection_id) %>% 
  tally() %>% 
  rename(n_draw = n)

trim_df <- trim_df %>% 
  left_join(n_draws, by = "collection_id")

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Random draws of coefs from first stage ---------------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## Function to create random draws of first stage coefficients
draw_coefs <- function(n, cwd_est, pet_est, int_est, cwd_ste, pet_ste, int_ste, 
                       cwd_pet_cov, pet_int_cov, cwd_int_cov){
  mu <- c("cwd_coef" = cwd_est, 
          "pet_coef" = pet_est, 
          "int_coef" = int_est)
  vcov <- matrix(data = NA, nrow = 3, ncol = 3)
  vcov[1,1] <- cwd_ste^2
  vcov[2,2] <- pet_ste^2
  vcov[3,3] <- int_ste^2
  vcov[1,2] <- cwd_pet_cov
  vcov[2,1] <- cwd_pet_cov
  vcov[1,3] <- cwd_int_cov
  vcov[3,1] <- cwd_int_cov
  vcov[2,3] <- pet_int_cov
  vcov[3,2] <- pet_int_cov
  
  draw <- mvrnorm(n, mu, vcov)
  draw <- as_tibble(draw)
  draw$iter_idx <- seq(1,n)
  draw <- draw %>% select(iter_idx, cwd_coef, pet_coef, int_coef)
  return(draw)
}

## Create needed number (n_draw) of random draws of first stage coefficients for each site
trim_df <- trim_df %>% 
  drop_na()

mc_df <- trim_df %>%
  mutate(coef_draws = pmap(list(n = trim_df$n_draw + 1, 
                                cwd_est = trim_df$estimate_cwd.an, 
                                pet_est = trim_df$estimate_pet.an,
                                int_est = trim_df$estimate_intercept, 
                                cwd_ste = trim_df$std.error_cwd.an,
                                pet_ste = trim_df$std.error_pet.an, 
                                int_ste = trim_df$std.error_intercept,
                                cwd_pet_cov = trim_df$cov_cwd_pet, 
                                cwd_int_cov = trim_df$cov_int_cwd,
                                pet_int_cov = trim_df$cov_int_pet), 
                           draw_coefs))


## Unnest to create dataframe of n_site X n_draw coefficient estimates
mc_df <- mc_df %>% 
  unnest(coef_draws) %>% 
  select(collection_id, iter_idx, cwd_coef, pet_coef, int_coef, cwd.spstd, 
         pet.spstd, latitude, longitude, cwd_errorweights, pet_errorweights, int_errorweights)


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Merge first stage draws back to bootstrap dataframe -------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
block_draw_df <- block_draw_df %>% 
  group_by(collection_id) %>% 
  mutate(iter_idx = 1:n())

block_draw_df <- block_draw_df %>% 
  left_join(mc_df, by = c("collection_id", "iter_idx"))

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Export first stage draws to pull summary stats -------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
block_draw_df %>% 
  # select(boot_id, collection_id, cwd_coef, pet_coef, int_coef, cwd.spstd, pet.spstd) %>% 
  write_rds(paste0(wdir, "2_output/second_stage/mc_sample.gz"), compress = "gz")


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Run bootstrap estimation of second stage model -------------------------
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
## Function defining main second stage model
run_ss <- function(data, outcome = "cwd_coef"){
  if (outcome == "cwd_coef") {
    error_weights = data$cwd_errorweights
  } else if (outcome == "pet_coef") {
    error_weights = data$pet_errorweights
  } else if (outcome == "int_coef") {
    error_weights = data$int_errorweights
  }
  formula <- as.formula(paste(outcome, " ~ cwd.spstd + I(cwd.spstd^2) + pet.spstd + I(pet.spstd^2)"))
  mod <- lm(formula, data=data, weights = error_weights)
  # mod <- lm(formula, data=data)
  coefs <- mod %>% 
    tidy() %>% 
    pull(estimate) 
  return(coefs)
}


## Function to run second stage model for first stage CWD, 
## PET and Intercept terms and organize coefficients
bs_ss <- function(data){
  # data <- data %>% # Needed to add this since block bootstrap is returning nested tibble
  #   unnest(cols = c(data))
  cwd_mod <- data %>% 
    run_ss(outcome = "cwd_coef")
  pet_mod <- data %>% 
    run_ss(outcome = "pet_coef")
  int_mod <- data %>% 
    run_ss(outcome = "int_coef")
  # return(list("int_mod" = c(int_mod),
  #             "cwd_mod" = c(cwd_mod),
  #             "pet_mot" = c(pet_mod)))
  return(list(int_int = int_mod[1],
              int_cwd = int_mod[2],
              int_cwd2 = int_mod[3],
              int_pet = int_mod[4],
              int_pet2 = int_mod[5],
              cwd_int = cwd_mod[1],
              cwd_cwd = cwd_mod[2],
              cwd_cwd2 = cwd_mod[3],
              cwd_pet = cwd_mod[4],
              cwd_pet2 = cwd_mod[5],
              pet_int = pet_mod[1],
              pet_cwd = pet_mod[2],
              pet_cwd2 = pet_mod[3],
              pet_pet = pet_mod[4],
              pet_pet2 = pet_mod[5]))
}

bs_constant <- function(data){
  # data <- data %>% # Needed to add this since block bootstrap is returning nested tibble
  #   unnest(cols = c(data))
  const_sens <- data %>% 
    summarise(cwd_const_sens = weighted.mean(cwd_coef, cwd_errorweights),
          pet_const_sens = weighted.mean(pet_coef, pet_errorweights),
          int_const_sens = weighted.mean(int_coef, pet_errorweights))
  return(const_sens)
}


## Create dataframe holding bootstrap samples
boot_df <- block_draw_df %>%
  select(-iter_idx) %>% 
  group_by(boot_id) %>% 
  nest()


## Estimate second stage models
boot_df <- boot_df %>% 
  mutate(const_sens = map(.x = data, .f = bs_constant)) %>%
  unnest_wider(const_sens) %>%
  mutate(estimates = map(.x = data, .f = bs_ss)) %>% 
  unnest_wider(estimates) %>% 
  select(-data) %>% 
  ungroup()


## Save out bootstrapped coefficients
write_rds(boot_df, paste0(wdir, "2_output/second_stage/ss_bootstrap.rds"))

```








# Running Step 7 - Figure 2 From Script









```{r}
#===============================================================================
# Species deep dive plots
# 
# 
#===============================================================================

#===============================================================================
# 1) Pkg imports ---------
#===============================================================================
library(tidyverse)
library(dbplyr)
library(RSQLite)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(rgeos)
library(stringr)
library(raster)
library(rgdal)
library(viridis)
library(patchwork)
library(effects)
library(dplR)
library(here)
select <- dplyr::select


base_text_size = 12
theme_set(
  theme_bw(base_size = base_text_size)+
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          # text=element_text(family ="Helvetica"),
          panel.background = element_rect(fill='transparent'), 
          plot.background = element_rect(fill='transparent', color=NA), 
          legend.background = element_rect(fill='transparent')))

pt_size = .pt

#===============================================================================
# 2) Data imports  ---------
#===============================================================================
### Define path
wdir <- 'remote/'

# 1. Site-level regressions
flm_df <- read_csv(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "site_pet_cwd_std_augmented.csv"))

# 2. Species range maps
range_sf <- st_read(here("~", "..", "..", "capstone", "climatree", "dataverse-archive", "merged_ranges_dissolve.shp"))
#range_sf <- st_read(range_file)

# 3. Site information
site_smry <- read_csv(here("~", "..", "..", "capstone", "climatree", "dataverse-archive", "site_summary.csv"))
site_smry <- site_smry %>% 
  select(collection_id, sp_id, latitude, longitude) %>% 
  mutate(species_id = tolower(sp_id)) %>% 
  select(-sp_id)
# site_loc <- site_smry %>% 
#   select(collection_id, latitude, longitude)
# flm_df <- flm_df %>% 
#   left_join(site_loc, by = "collection_id")

# # 4. Species information
# sp_info <- read_csv(paste0(wdir, 'species_gen_gr.csv'))
# sp_info <- sp_info %>% 
#   select(species_id, genus, gymno_angio, family)
# site_smry <- site_smry %>% 
#   left_join(sp_info, by = c("species_id"))

# 5. Prediction rasters
rwi_list <- list.files(paste0(wdir, "2_output/predictions/sp_rwi/"), pattern = ".gz", full.names = TRUE)

rwi_list <- list.files(here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output","sp_rwi"), pattern = ".gz", full.names = TRUE)
sp_predictions <- do.call('rbind', lapply(rwi_list, readRDS))

# 6. Dendro examples - note: exporting two pipo sites in first stage script
dendro_ex <- read_csv(paste0(wdir, "2_output/first_stage/example_sites.csv"))

# 7. Raw dendro file for one site
rwl_path <- paste0(wdir, "1_input_processed/dendro/ca585.rwl")
rwl_dat <- read.tucson(paste0(rwl_path))



#===============================================================================
# Prep climate / prediction data  ---------
#===============================================================================
# Define species
flm_df %>% group_by(species_id) %>% tally() %>% arrange(desc(n))

spp_code <- 'pipo'


trim_df <- flm_df %>% 
  filter(species_id == spp_code)

spp_predictions <- sp_predictions %>% 
  filter(sp_code == spp_code)

# sp_fut <- (spp_predictions %>% 
#              pull(clim_future_sp))[[1]]
# names(sp_fut) <- c("cwd.fut", "pet.fut")
# 
# sp_hist <- (spp_predictions %>% 
#               pull(clim_historic_sp))[[1]]
# sp_sens  <- (spp_predictions %>% 
#                pull(sensitivity))[[1]]
# sp_rwi  <- (spp_predictions %>% 
#               pull(rwi_predictions))[[1]]
# names(sp_rwi) <- "rwi"
# 
# 
# clim_compare <- brick(c(sp_fut, sp_hist, sp_sens, sp_rwi))
# clim_compare <- clim_compare %>% 
#   as.data.frame(xy = TRUE)


#===============================================================================
# Define example sites  ---------
#===============================================================================
# Pull relevant ITRDB sites
trim_df <- trim_df %>%
  drop_na() %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

high_sens = "CO559"
low_sens = "CA585"

high_coords <- trim_df %>% 
  filter(collection_id == high_sens) %>% 
  pull(geometry)
low_coords <- trim_df %>% 
  filter(collection_id == low_sens) %>% 
  pull(geometry)

high_val <- trim_df %>% 
  filter(collection_id == high_sens) %>% 
  pull(estimate_cwd.an) %>% 
  round(digits = 3)

low_val <- trim_df %>% 
  filter(collection_id == low_sens) %>% 
  pull(estimate_cwd.an) %>% 
  round(digits = 3)


high_fs <- trim_df %>% filter(collection_id == high_sens)
low_fs <- trim_df %>% filter(collection_id == low_sens)

high_lab <- paste0("sensitivity = ", as.character(high_val))
low_lab <- paste0("sensitivity = ", as.character(low_val))

high_color <- "#404788"
low_color <- "#efca2a"
low_color <- "#1b9e77"

#440154FF

#===============================================================================
# Step 1: data and detrending  ---------
#===============================================================================
### Map of ITRDB sites and species range

# Pull relevant range map
sp_range <- range_sf %>% 
  filter(sp_code == spp_code)
sp_bbox <- st_bbox(sp_range)

lon_lims <- c(sp_bbox$xmin - 1, sp_bbox$xmax + 1)
lat_lims <- c(sp_bbox$ymin - 1, sp_bbox$ymax + 1)

# Plot species ranges
world <- ne_coastline(scale = "medium", returnclass = "sf")
map <- ggplot(trim_df, aes(x = Longitude, y = Latitude))
  
  
map <- ggplot() +
  geom_sf(data = world) +
  geom_sf(data = sp_range, fill = 'black', alpha = .2, colour = NA) +
  geom_sf(data = trim_df, color = '#B0357B', fill = '#B0357B', alpha = .4) +
  ylab("Latitude")+
  xlab("Longitude")+
  # theme(axis.text.x=element_text(size=base_text_size - 2),
  #       axis.text.y=element_text(size = base_text_size - 2))+
  coord_sf(xlim = lon_lims, ylim = lat_lims, expand = FALSE) +
  scale_x_continuous(breaks=seq(-120,100,10)) +
  geom_point(aes(x = high_coords[[1]][1], y = high_coords[[1]][2]), color = high_color, size = 3) +
  geom_point(aes(x = low_coords[[1]][1], y = low_coords[[1]][2]), color = low_color, size = 3) +
  geom_segment(
    data = trim_df,
    x = -105, y = 50,
    xend = high_coords[[1]][1], yend = high_coords[[1]][2] + 1.3,
    lineend = "round",
    linejoin = "round",
    linewidth = 1,
    arrow = arrow(length = unit(0.05, "inches"), type = "closed"),
    colour = high_color
  ) +
  geom_label(aes(x = -105, y = 50, label = "Site A"), fill = high_color, color = "white", size = 5, label.size = NA) +
  geom_segment(
    data = trim_df,
    # x = -low_coords[[1]][1] - 20, y = low_coords[[1]][2],
    x = -120, y = 25,
    # x = -120, y = 25,
    xend = low_coords[[1]][1], yend = low_coords[[1]][2] - 1.3,
    lineend = "round",
    linejoin = "round",
    linewidth = 1, 
    arrow = arrow(length = unit(0.05, "inches"), type = "closed"),
    colour = low_color
  ) +
  geom_label(aes(x = -119, y = 25, label = "Site B"), fill = low_color, color = "white", size = 5, label.size = NA)

map
# ggsave(paste0(wdir, 'figures/Methods figure/TransparentFigs/map_ex.png'), plot = map, bg= 'transparent', width = 2.25, height = 2.9)



### Illustrate detrending
rwl <- rwl_dat %>% select(PPP02B)
rwi <- rwl %>% 
  select(PPP02B) %>% 
  detrend(method = "Spline", make.plot = TRUE)
detrend_df <- tibble("RWL" = rwl$PPP02B, "RWI" = rwi$PPP02B) %>% 
  mutate(Spline = RWL / RWI) %>% 
  drop_na() %>% 
  mutate(Age = row_number(),
         Detrend_spline = 1)

rwl_plot <- ggplot(data = detrend_df) +
  geom_line(aes(x = Age, y = RWL), size = 0.5) +
  geom_line(aes(x = Age, y = Spline),linetype="dashed", linewidth = 0.25) +
  ylab("RWL (mm)") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())


rwi_plot <- ggplot(data = detrend_df) +
  geom_line(aes(x = Age, y = RWI), size = 0.5) +
  geom_line(aes(x = Age, y = Detrend_spline),linetype="dashed", size = 0.25) +
  ylab("RWI") +
  xlab("Age (years)")

despline_plot <- rwl_plot / rwi_plot
despline_plot

# ggsave(paste0(wdir, 'figures/Methods figure/TransparentFigs/despline.png'), plot = despline_plot, bg= 'transparent', width = 2, height = 2.9)


panel_a <- map | despline_plot
panel_a
ggsave(paste0(wdir, '3_results/figures/methods_panels/step_1.png'), plot = panel_a, bg= 'transparent', width = 4.25, height = 2.9, dpi = 600)

#===============================================================================
# Step 2: Climatic range  ---------
#===============================================================================
### Plot of climatic range with ITRDB sites
xmin <- -1.5
xmax <- 2
hex <- spp_predictions %>% 
  ggplot(aes(x = cwd_hist, y = pet_hist)) +
  geom_density_2d(color = 'grey') +
  # geom_density_2d(colour = "black") +
  #geom_density_2d_filled(alpha = .6) +
  xlim(xmin, xmax) +
  ylim(xmin, xmax) +
  # labs(fill = "Number of cells") +
  ylab("Historic PET\n(Deviation from species mean)") +
  xlab("Historic CWD\n(Deviation from species mean)") + 
  coord_fixed() +
  guides(fill=F, colour=F)+
  geom_point(data = trim_df, aes(x = cwd.spstd, y = pet.spstd), colour = '#B0357B', alpha = 0.4, size = 0.75) +
  geom_point(aes(x = high_fs$cwd.spstd, y = high_fs$pet.spstd), color = high_color, size = 3) +
  geom_point(aes(x = low_fs$cwd.spstd, y = low_fs$pet.spstd), color = low_color, size = 3) +
  geom_segment(
    x = 0.5, y = -1.3,
    xend = high_fs$cwd.spstd + 0.2, yend = high_fs$pet.spstd - 0.04,
    lineend = "round",
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.05, "inches"), type = "closed"),
    colour = high_color
  ) +
  geom_label(aes(x = 0.5, y = -1.3, label = "Site A"), fill = high_color, color = "white", size = 5, label.size = NA) +
  geom_segment(
    x = 1, y = -0.8,
    xend = low_fs$cwd.spstd + 0.2, yend = low_fs$pet.spstd - 0.04,
    lineend = "round",
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.05, "inches"), type = "closed"),
    colour = low_color
  ) +
  geom_label(aes(x = 1, y = -0.8, label = "Site B"), fill = low_color, color = "white", size = 5, label.size = NA)
hex

ggsave(paste0(wdir, '3_results/figures/methods_panels/step_2.png'), plot = hex, bg= 'transparent', width = 2.9, height = 2.9, dpi = 600)



#===============================================================================
# Step 3: First stage for example sites  ---------
#===============================================================================
high_ex <- dendro_ex %>% 
  filter(collection_id == high_sens) %>% 
  mutate(label="high")
low_ex <- dendro_ex %>% 
  filter(collection_id == low_sens) %>% 
  mutate(label="low")

both_ex <- high_ex %>% 
  rbind(low_ex)

both_fig <- both_ex %>%
  ggplot(aes(x = cwd.an.spstd, y = rwi, color=label, fill=label)) +
  geom_point( alpha=.1) +
  scale_fill_manual(values = c(high_color, low_color)) +
  scale_color_manual(values = c(high_color, low_color)) +
  geom_smooth(method="lm") +
  #theme_bw(base_size = 25) +
  #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  #plot.title = element_text(hjust = 0.5))+
  ylab("Ring width index")+
  xlab("Climatic water deficit") +
  ylim(c(0,3)) +
  xlim(c(-1.25, 0))+
  guides(fill=F, color=F)+
  geom_label(aes(x = -1.05, y = 2.5, label = "Site A"), fill = high_color, color = "white", size = 5, label.size = NA) +
  geom_label(aes(x = -0.4, y = 2.5, label = "Site B"), fill = low_color, color = "white", size = 5, label.size = NA)
# 
#   annotate("text", x = -1.05, y = 2.5, label = paste("Site A"), color = high_color, size = 12/ pt_size)+
#   annotate("text", x = -0.4, y = 2.5, label = paste("Site B"), color = low_color, size = 12/ pt_size)

both_fig
ggsave(paste0(wdir, '3_results/figures/methods_panels/step_3.png'), plot = both_fig, bg= 'transparent', width = 3.5, height = 2.9, dpi = 600)


#===============================================================================
# Step 4: Second stage variation in sensitivity  ---------
#===============================================================================
### Plot of cwd sensitivity against cwd.spstd
mod <- lm(estimate_cwd.an ~ cwd.spstd + I(cwd.spstd^2) + pet.spstd + I(pet.spstd^2), data = trim_df)
eff = effect("cwd.spstd", mod, partial.residuals=T)
closest <- function(x, x0) apply(outer(x, x0, FUN=function(x, x0) abs(x - x0)), 1, which.min)
x.fit <- unlist(eff$x.all)
trans <- I
x <- data.frame(lower = eff$lower, upper = eff$upper, fit = eff$fit, cwd = eff$x$cwd.spstd)
xy <- data.frame(x = x.fit, y = x$fit[closest(trans(x.fit), x$cwd)] + eff$residuals)

partial_plot <- ggplot(filter(x,cwd <=1&fit<=1), aes(x = cwd, y = fit, color="black")) +
  #theme_bw(base_size = 20)+
  #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  #plot.title = element_text(hjust = 0.5))+
  geom_line(size = 1,color="black", fill="black") +
  #scale_color_gradient()+
  #geom_smooth(method="lm", color="#21908CFF", fill="#21908CFF")+
  geom_point(data = filter(xy, x<=1&y<=1), aes(x = x, y = y, color= "black"), alpha=.5) +
  scale_colour_manual(values = "black")+
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.3, fill = "black") +
  xlab("Historic CWD\n(Deviation from species mean)") +
  ylab("Partial effect of CWD\non CWD sensitivity")+
  guides(scale = "none", color=F) +
  geom_point(aes(x = high_fs$cwd.spstd, y = high_fs$estimate_cwd.an), color = high_color, size = 3) +
  geom_point(aes(x = low_fs$cwd.spstd, y = low_fs$estimate_cwd.an), color = low_color, size = 3) +
  geom_segment(
    x = -0.2, y = -2.4,
    xend = high_fs$cwd.spstd + 0.1, yend = high_fs$estimate_cwd.an - 0.05,
    lineend = "round",
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.05, "inches"), type = "closed"),
    colour = high_color
  ) +
  geom_label(aes(x = -0.2, y = -2.4, label = "Site A"), fill = high_color, color = "white", size = 5, label.size = NA) +
  geom_segment(
    x = -1, y = 0.8,
    xend = low_fs$cwd.spstd - 0.1, yend = low_fs$estimate_cwd.an + 0.1,
    lineend = "round",
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.05, "inches"), type = "closed"),
    colour = low_color
  ) +
  geom_label(aes(x = -1, y = 0.7, label = "Site B"), fill = low_color, color = "white", size = 5, label.size = NA)
  # geom_smooth(data = xy, aes(x = trans(x), y = y), 
#             method = "loess", span = 2/3, linetype = "dashed", se = FALSE)
partial_plot

ggsave(paste0(wdir, '3_results/figures/methods_panels/step_4.png'), plot = partial_plot, bg= 'transparent', width = 3.75, height = 3.05, dpi = 600)

# combined_plot <- (map_ex | both_fig) / (sens_niche | partial_plot)+ plot_layout(widths = c(1,4))
# combined_plot
# combined_plot <- (map_ex | high_ex / low_ex) / (sens_niche | partial_plot)
# #ggsave(paste0(wdir, "figures\\", "5_sp_example.svg"), combined_plot, width = 15, height = 12)


#===============================================================================
# Step 5: Prediction of sensitivity  ---------
#===============================================================================
spp_predictions <- spp_predictions %>% filter(abs(cwd_hist) < 2) ## TODO - FIgure out correct cut-off for predictions

### Map of CWD sensitivity
cwd_sens_map <- ggplot() +
  geom_sf(data = world) +
  geom_raster(data = spp_predictions %>% drop_na(), aes(x = x, y = y, fill = cwd_sens)) +
  #theme_bw(base_size = 22)+
  theme(legend.position = c(.15,.18))+
  ylab("Latitude")+
  xlab("Longitude")+
  guides(fill=guide_legend("Sens."))+
  #scale_fill_viridis_c(direction = -1) +
  scale_fill_viridis(option="mako", direction = -1)+
  coord_sf(xlim = lon_lims, ylim = lat_lims, expand = FALSE) +
  scale_x_continuous(breaks=seq(-120,100,10)) +
  theme(axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        # axis.text.x=element_text(size=base_text_size - 6),
        # axis.text.y=element_text(size = base_text_size - 6),
        legend.key.size = unit(8, "pt"),
        legend.title=element_text(size=base_text_size - 2), 
        legend.text=element_text(size=base_text_size - 4))+
  theme()
cwd_sens_map

ggsave(paste0(wdir, '3_results/figures/methods_panels/step_5.png'), plot = cwd_sens_map, bg= 'transparent', width = 2.25, height = 2.9, dpi = 600)


#===============================================================================
# Step 5: Prediction of RWI change  ---------
#===============================================================================
### Map of CWD change
spp_predictions <- spp_predictions %>% 
  mutate(cwd_change = cwd_cmip_end_mean - cwd_cmip_start_mean,
         pet_change = pet_cmip_end_mean - pet_cmip_start_mean)

cwd_change_map <- ggplot() +
  geom_sf(data = world) +
  geom_raster(data = spp_predictions %>% drop_na(), aes(x = x, y = y, fill = cwd_change)) +
  #theme_bw(base_size = 22)+
  guides(fill=guide_legend(" CWD"))+
  theme(legend.position = c(.18,.15))+
  ylab("Latitude")+
  xlab("Longitude")+
  #scale_fill_viridis_c(direction = -1) +
  scale_fill_viridis(option="magma")+
  coord_sf(xlim = lon_lims, ylim = lat_lims, expand = FALSE) +
  scale_x_continuous(breaks=seq(-120,100,10)) +
  theme(axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        # axis.text.x=element_text(size=base_text_size - 6),
        # axis.text.y=element_text(size = base_text_size - 6),
        legend.key.size = unit(8, "pt"),
        legend.title=element_text(size=base_text_size - 2), 
        legend.text=element_text(size=base_text_size - 4))
cwd_change_map

ggsave(paste0(wdir, '3_results/figures/methods_panels/step_6a.png'), plot = cwd_change_map, bg= 'transparent', width = 2.25, height = 2.9, dpi = 600)


### Map of predicted RWI
rwi_map <- ggplot() +
  geom_sf(data = world) +
  geom_raster(data = spp_predictions %>% drop_na(), aes(x = x, y = y, fill = rwi_pred_change_mean)) +
  # theme_bw(base_size = 12)+
  ylab("Latitude")+
  xlab("Longitude")+
  scale_fill_viridis_c(direction = -1) +
  #scale_fill_viridis(option="mako")+
  guides(fill=guide_legend(title=" RWI"))+
  coord_sf(xlim = lon_lims, ylim = lat_lims, expand = FALSE) +
  scale_x_continuous(breaks=seq(-120,100,10)) +
  theme(legend.position = c(.18,.15),
        # axis.text.x=element_text(size=base_text_size - 6),
        # axis.text.y=element_text(size = base_text_size - 6),
        axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        legend.key.size = unit(8, "pt"),
        legend.title=element_text(size=base_text_size - 2), 
        legend.text=element_text(size=base_text_size - 4))
rwi_map

ggsave(paste0(wdir, '3_results/figures/methods_panels/step_6b.png'), plot = rwi_map, bg= 'transparent', width = 2.25, height = 2.9, dpi = 600)

```

