---
title: "Exploring Raw Tree Data"
subtitle: "Isolating 20 Most Sampled Tree Species"
author: "Briana Barajas"
date: 2024-01-28
---

## Preparation

Set-up chunk

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

Load libraries

```{r}
library(tidyverse)
library(here)
library(gghighlight)

remote_wdir <- here("~","..", "..", "capstone", "climatree")
```

## Find 20 Most Sampled Species

### Read Dendro Data

```{r}
## ==================================================
##                 read in data                  ----
## ==================================================
# read in tree ring data
rwi_long <- read_csv(here(remote_wdir, "dataverse-archive", "rwi_long.csv"))

# read in site summary table
site_smry <- read_csv(here(remote_wdir, "dataverse-archive", "site_summary.csv"))

# read in species metadata
species_metadata <- read_csv(here(remote_wdir, "dataverse-archive", "species_metadata.csv"))
```

### Wrangle and Join Dendro Data

```{r}
## ==================================================
##                 prep for join                ----
## ==================================================

# ...... update rwi data ......
rwi_clean <- rwi_long %>% 
  
  # remove cols not being used to speed up join 
  select(-c(rwl, rwi_ar, rwi_nb)) %>% 
  
  # filter out predictive sample years (2019-2065)
  filter(year < 2019)


# ...... update species metadata ......
species_metadata <- species_metadata %>% 
  rename(sp_code = species_id)


# ..... update site smry data .....
site_smry <- site_smry %>%
  select(collection_id, sp_id) %>% 
  mutate(location_id = collection_id) %>%
  
  # change sp_id to lower case
  mutate(sp_code = tolower(sp_id)) %>% 
  
  # remove sp_id column
  select(-sp_id)

## ==================================================
##                   join data                   ----
## ==================================================

# ..... join rwi, metadata, and site summary .....
rwi_species <- rwi_clean %>% 
  
  # join rwi to site_summary by collection id
  left_join(y = site_smry, by = 'collection_id') %>% 
  
  #join with species metadata
  left_join(y = species_metadata, by = "sp_code")
```

### Plot Species With Most Tree-Ring Samples

```{r, plot top spp}
## ==================================================
##                  plot 20 top spp              ----
## ==================================================
# ..... create df listing individual trees .....
indv_tree_spp <- rwi_species %>% 
  group_by(tree) %>% 
  summarise(sp_code = first(sp_code), 
            spp = first(spp),
            common_name = first(common_name))

# ..... count occurence of each species .....
sp_count <- plyr::count(indv_tree_spp$spp) %>% 
  rename(spp = x)

# plot top 20 collection ID counts
sp_count %>% 
  drop_na(spp) %>% 
  slice_max(order_by = freq, n = 20) %>% 
  ggplot() +
  geom_col(aes(x = fct_reorder(spp, freq), y = freq), fill = "palegreen4") +
  labs(x = "Genus Species",
       y = "Number of Trees Sampled",
       title = "20 Most Prominent Species in Tree Core Dataset") +
  geom_text(aes(x = fct_reorder(spp, freq), y = freq,
                label = freq), hjust = 1.2, color = "white", size = 3.5) +
  coord_flip() +
  theme_minimal() #+
  # annotate("rect", 
  #          xmin = 10.5, xmax = 6.5, 
  #          ymin = -1, ymax = 731, 
  #          fill = NA, color = "maroon",
  #          linewidth = 1.5)
```
Customize plot for 
```{r, eval=FALSE}
# plot top 20 collection ID counts
sp_count %>% 
  drop_na(spp) %>% 
  slice_max(order_by = freq, n = 10) %>% 
  ggplot() +
  geom_col(aes(x = fct_reorder(spp, freq), y = freq), fill = "midnightblue") +
  labs(x = "Genus Species",
       y = "Number of Trees Sampled",
       title = "Top 10 Species") +
  geom_text(aes(x = fct_reorder(spp, freq), y = freq,
                label = freq), hjust = 1.2, color = "white", size = 3.5) +
  coord_flip() +
  theme_classic() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(hjust=0.5))

```


## Export Subset

```{r pcma subset}
## ==================================================
##                 create pcma subset            ----
## ==================================================
# subset most sampled species
pcma_rwi <- rwi_species %>% 
  filter(spp == "Picea mariana")

## ==================================================
##           export subset to prelim-maps       ----
## ==================================================
write_csv(pcma_rwi, here("~", "..", "..", "capstone", "climatree", "output-data", "step-1-output", "pcma_rwi.csv"))
```




